- name: Install Postfix, Dovecot, MariaDB, rkhunter, and binutils
  hosts: target
  become: yes
  tasks:
    - name: Install Postfix, Dovecot, MariaDB, rkhunter, and binutils
      package:
         name:
            - postfix
            - postfix-mysql
            - postfix-doc
            - mariadb-client
            - mariadb-server
            - openssl
            - getmail4
            - rkhunter
            - binutils
            - dovecot-imapd
            - dovecot-pop3d 
            - dovecot-mysql
            - dovecot-sieve
            - dovecot-lmtpd 
         state: present
    - name: Reconfigure Postfix to our needs
      expect:
         command: dpkg-reconfigure -f readline postfix
         echo: yes
         responses:
            - Konfiguration: 'Internet-Site'
            - System-E-Mail-Name: 

