- name: Perfect Server Setup
  hosts: target
  become: yes
  roles:
    - install-python-libs
    - update-upgrade
    - change-to-bash
    - disable-apparmor
    - disable-sendmail
    - install-tools
    - install-mariadb
    - install-dovecot
    - install-postfix
    - install-virus-protection
    - install-spam-protection
    - install-webserver-etc
    - enable-ruby
    - enable-php-opcode-cache
    - install-php-fpm
    - install-hiphop-vm
    - install-lets-encrypt
    - install-mailman
    - install-pureftpd-quota
    - install-bind-dns-server
    - install-vlogger-webalizer-awstats
    - install-jailkit
    - install-fail2ban
    - install-ufw
    - install-roundcube
    - install-isp-config
