- name: Server hardening
  hosts: target
  become: yes
  roles:
    - update-upgrade
    - restart-server
    - secure-ssh
    - use-logwatch
    - use-apticron
    - forward-local-root-mails
    - use-monit
