- name: Stop service AppArmor
  service:
     name: apparmor
     state: stopped
  ignore_errors: yes
- name: Disable AppArmor
  service:
     name: apparmor
     enabled: no
  ignore_errors: yes
- name: Uninstall AppArmor
  apt:
     name:
        - apparmor
        - apparmor-utils
     state: absent
     purge: yes
     autoremove: yes
