- name: Install Redis (for rpamd)
  package:
    name:
      - redis-server
      - lsb-release
    state: present
- name: Get lsb name of host
  command: "lsb_release -c -s"
  register: host_lsb_name
- name: Add an Apt signing key for rspamd.com
  apt_key:
    url: https://rspamd.com/apt-stable/gpg.key
    state: present
- name: Add apt-sources to rpamd.com
  template:
    src: rspamd.list
    dest: /etc/apt/sources.list.d/rspamd.list
- name: "Update apt cache"
  apt:
    update_cache: yes
- name: Install rspamd
  package:
    name: rspamd
    state: present
- name: Activate Redis in Rspamd configuration
  lineinfile:
    path: /etc/rspamd/local.d/redis.conf
    line: servers = "127.0.0.1";
    create: yes
- name: Increase the Rspamd history
  lineinfile:
    path: /etc/rspamd/local.d/history_redis.conf
    line: nrows = 2500;
    create: yes
- name: Enable compression for Rspamd
  lineinfile:
    path: /etc/rspamd/local.d/history_redis.conf
    line: compress = true;
- name: Show the subject in the history
  lineinfile:
    path: /etc/rspamd/local.d/history_redis.conf
    line: subject_privacy = false;
- name: Restart Rspamd
  service:
    name: rspamd
    state: restarted
