- name: Install Fail2ban
  package:
    name:
      - fail2ban
- name: Copy apache filter to server
  copy:
    src: apache-404.local
    dest: /etc/fail2ban/filter.d/apache-404.local
- name: Copy jail.local to server
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
- name: Restart Fail2ban service
  service:
    name: fail2ban
    state: restarted
